// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: codegen_test.proto

#ifndef PROTOBUF_codegen_5ftest_2eproto__INCLUDED
#define PROTOBUF_codegen_5ftest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/empty.pb.h>
#include <google/protobuf/wrappers.pb.h>
#include "nanorpc/rpc_types.pb.h"
// @@protoc_insertion_point(includes)
namespace codegen_test {
class EnumType_wrapper__;
class EnumType_wrapper__DefaultTypeInternal;
extern EnumType_wrapper__DefaultTypeInternal _EnumType_wrapper___default_instance_;
class Method_V_biuIUsSfdEAWM_args__;
class Method_V_biuIUsSfdEAWM_args__DefaultTypeInternal;
extern Method_V_biuIUsSfdEAWM_args__DefaultTypeInternal _Method_V_biuIUsSfdEAWM_args___default_instance_;
class StructType;
class StructTypeDefaultTypeInternal;
extern StructTypeDefaultTypeInternal _StructType_default_instance_;
}  // namespace codegen_test
namespace google {
namespace protobuf {
class BoolValue;
class BoolValueDefaultTypeInternal;
extern BoolValueDefaultTypeInternal _BoolValue_default_instance_;
class BytesValue;
class BytesValueDefaultTypeInternal;
extern BytesValueDefaultTypeInternal _BytesValue_default_instance_;
class DoubleValue;
class DoubleValueDefaultTypeInternal;
extern DoubleValueDefaultTypeInternal _DoubleValue_default_instance_;
class Empty;
class EmptyDefaultTypeInternal;
extern EmptyDefaultTypeInternal _Empty_default_instance_;
class FloatValue;
class FloatValueDefaultTypeInternal;
extern FloatValueDefaultTypeInternal _FloatValue_default_instance_;
class Int32Value;
class Int32ValueDefaultTypeInternal;
extern Int32ValueDefaultTypeInternal _Int32Value_default_instance_;
class Int64Value;
class Int64ValueDefaultTypeInternal;
extern Int64ValueDefaultTypeInternal _Int64Value_default_instance_;
class StringValue;
class StringValueDefaultTypeInternal;
extern StringValueDefaultTypeInternal _StringValue_default_instance_;
class UInt32Value;
class UInt32ValueDefaultTypeInternal;
extern UInt32ValueDefaultTypeInternal _UInt32Value_default_instance_;
class UInt64Value;
class UInt64ValueDefaultTypeInternal;
extern UInt64ValueDefaultTypeInternal _UInt64Value_default_instance_;
}  // namespace protobuf
}  // namespace google
namespace nanorpc {
class RpcCall;
class RpcCallDefaultTypeInternal;
extern RpcCallDefaultTypeInternal _RpcCall_default_instance_;
class RpcEvent;
class RpcEventDefaultTypeInternal;
extern RpcEventDefaultTypeInternal _RpcEvent_default_instance_;
class RpcMessage;
class RpcMessageDefaultTypeInternal;
extern RpcMessageDefaultTypeInternal _RpcMessage_default_instance_;
class RpcObject;
class RpcObjectDefaultTypeInternal;
extern RpcObjectDefaultTypeInternal _RpcObject_default_instance_;
class RpcResult;
class RpcResultDefaultTypeInternal;
extern RpcResultDefaultTypeInternal _RpcResult_default_instance_;
class SInt32Value;
class SInt32ValueDefaultTypeInternal;
extern SInt32ValueDefaultTypeInternal _SInt32Value_default_instance_;
class SInt64Value;
class SInt64ValueDefaultTypeInternal;
extern SInt64ValueDefaultTypeInternal _SInt64Value_default_instance_;
class WideStringValue;
class WideStringValueDefaultTypeInternal;
extern WideStringValueDefaultTypeInternal _WideStringValue_default_instance_;
}  // namespace nanorpc

namespace codegen_test {

namespace protobuf_codegen_5ftest_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_codegen_5ftest_2eproto

enum EnumType {
  EnumValue0 = 0,
  EnumValue1 = 1,
  EnumValue2 = 2,
  EnumValue3 = 3,
  EnumValue4 = 4,
  EnumType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  EnumType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool EnumType_IsValid(int value);
const EnumType EnumType_MIN = EnumValue0;
const EnumType EnumType_MAX = EnumValue4;
const int EnumType_ARRAYSIZE = EnumType_MAX + 1;

const ::google::protobuf::EnumDescriptor* EnumType_descriptor();
inline const ::std::string& EnumType_Name(EnumType value) {
  return ::google::protobuf::internal::NameOfEnum(
    EnumType_descriptor(), value);
}
inline bool EnumType_Parse(
    const ::std::string& name, EnumType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EnumType>(
    EnumType_descriptor(), name, value);
}
// ===================================================================

class StructType : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:codegen_test.StructType) */ {
 public:
  StructType();
  virtual ~StructType();

  StructType(const StructType& from);

  inline StructType& operator=(const StructType& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StructType& default_instance();

  static inline const StructType* internal_default_instance() {
    return reinterpret_cast<const StructType*>(
               &_StructType_default_instance_);
  }

  void Swap(StructType* other);

  // implements Message ----------------------------------------------

  inline StructType* New() const PROTOBUF_FINAL { return New(NULL); }

  StructType* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const StructType& from);
  void MergeFrom(const StructType& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StructType* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string string_value = 11;
  void clear_string_value();
  static const int kStringValueFieldNumber = 11;
  const ::std::string& string_value() const;
  void set_string_value(const ::std::string& value);
  #if LANG_CXX11
  void set_string_value(::std::string&& value);
  #endif
  void set_string_value(const char* value);
  void set_string_value(const char* value, size_t size);
  ::std::string* mutable_string_value();
  ::std::string* release_string_value();
  void set_allocated_string_value(::std::string* string_value);

  // string wstring_value = 12;
  void clear_wstring_value();
  static const int kWstringValueFieldNumber = 12;
  const ::std::string& wstring_value() const;
  void set_wstring_value(const ::std::string& value);
  #if LANG_CXX11
  void set_wstring_value(::std::string&& value);
  #endif
  void set_wstring_value(const char* value);
  void set_wstring_value(const char* value, size_t size);
  ::std::string* mutable_wstring_value();
  ::std::string* release_wstring_value();
  void set_allocated_wstring_value(::std::string* wstring_value);

  // bool bool_value = 1;
  void clear_bool_value();
  static const int kBoolValueFieldNumber = 1;
  bool bool_value() const;
  void set_bool_value(bool value);

  // int32 int32_value = 2;
  void clear_int32_value();
  static const int kInt32ValueFieldNumber = 2;
  ::google::protobuf::int32 int32_value() const;
  void set_int32_value(::google::protobuf::int32 value);

  // int64 int64_value = 4;
  void clear_int64_value();
  static const int kInt64ValueFieldNumber = 4;
  ::google::protobuf::int64 int64_value() const;
  void set_int64_value(::google::protobuf::int64 value);

  // uint32 uint32_value = 3;
  void clear_uint32_value();
  static const int kUint32ValueFieldNumber = 3;
  ::google::protobuf::uint32 uint32_value() const;
  void set_uint32_value(::google::protobuf::uint32 value);

  // sint32 sint32_value = 6;
  void clear_sint32_value();
  static const int kSint32ValueFieldNumber = 6;
  ::google::protobuf::int32 sint32_value() const;
  void set_sint32_value(::google::protobuf::int32 value);

  // uint64 uint64_value = 5;
  void clear_uint64_value();
  static const int kUint64ValueFieldNumber = 5;
  ::google::protobuf::uint64 uint64_value() const;
  void set_uint64_value(::google::protobuf::uint64 value);

  // sint64 sint64_value = 7;
  void clear_sint64_value();
  static const int kSint64ValueFieldNumber = 7;
  ::google::protobuf::int64 sint64_value() const;
  void set_sint64_value(::google::protobuf::int64 value);

  // double double_value = 9;
  void clear_double_value();
  static const int kDoubleValueFieldNumber = 9;
  double double_value() const;
  void set_double_value(double value);

  // float float_value = 8;
  void clear_float_value();
  static const int kFloatValueFieldNumber = 8;
  float float_value() const;
  void set_float_value(float value);

  // .codegen_test.EnumType enum_value = 10;
  void clear_enum_value();
  static const int kEnumValueFieldNumber = 10;
  ::codegen_test::EnumType enum_value() const;
  void set_enum_value(::codegen_test::EnumType value);

  // @@protoc_insertion_point(class_scope:codegen_test.StructType)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr string_value_;
  ::google::protobuf::internal::ArenaStringPtr wstring_value_;
  bool bool_value_;
  ::google::protobuf::int32 int32_value_;
  ::google::protobuf::int64 int64_value_;
  ::google::protobuf::uint32 uint32_value_;
  ::google::protobuf::int32 sint32_value_;
  ::google::protobuf::uint64 uint64_value_;
  ::google::protobuf::int64 sint64_value_;
  double double_value_;
  float float_value_;
  int enum_value_;
  mutable int _cached_size_;
  friend struct  protobuf_codegen_5ftest_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class EnumType_wrapper__ : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:codegen_test.EnumType_wrapper__) */ {
 public:
  EnumType_wrapper__();
  virtual ~EnumType_wrapper__();

  EnumType_wrapper__(const EnumType_wrapper__& from);

  inline EnumType_wrapper__& operator=(const EnumType_wrapper__& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EnumType_wrapper__& default_instance();

  static inline const EnumType_wrapper__* internal_default_instance() {
    return reinterpret_cast<const EnumType_wrapper__*>(
               &_EnumType_wrapper___default_instance_);
  }

  void Swap(EnumType_wrapper__* other);

  // implements Message ----------------------------------------------

  inline EnumType_wrapper__* New() const PROTOBUF_FINAL { return New(NULL); }

  EnumType_wrapper__* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const EnumType_wrapper__& from);
  void MergeFrom(const EnumType_wrapper__& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(EnumType_wrapper__* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .codegen_test.EnumType value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  ::codegen_test::EnumType value() const;
  void set_value(::codegen_test::EnumType value);

  // @@protoc_insertion_point(class_scope:codegen_test.EnumType_wrapper__)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int value_;
  mutable int _cached_size_;
  friend struct  protobuf_codegen_5ftest_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Method_V_biuIUsSfdEAWM_args__ : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:codegen_test.Method_V_biuIUsSfdEAWM_args__) */ {
 public:
  Method_V_biuIUsSfdEAWM_args__();
  virtual ~Method_V_biuIUsSfdEAWM_args__();

  Method_V_biuIUsSfdEAWM_args__(const Method_V_biuIUsSfdEAWM_args__& from);

  inline Method_V_biuIUsSfdEAWM_args__& operator=(const Method_V_biuIUsSfdEAWM_args__& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Method_V_biuIUsSfdEAWM_args__& default_instance();

  static inline const Method_V_biuIUsSfdEAWM_args__* internal_default_instance() {
    return reinterpret_cast<const Method_V_biuIUsSfdEAWM_args__*>(
               &_Method_V_biuIUsSfdEAWM_args___default_instance_);
  }

  void Swap(Method_V_biuIUsSfdEAWM_args__* other);

  // implements Message ----------------------------------------------

  inline Method_V_biuIUsSfdEAWM_args__* New() const PROTOBUF_FINAL { return New(NULL); }

  Method_V_biuIUsSfdEAWM_args__* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Method_V_biuIUsSfdEAWM_args__& from);
  void MergeFrom(const Method_V_biuIUsSfdEAWM_args__& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Method_V_biuIUsSfdEAWM_args__* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string string_value = 11;
  void clear_string_value();
  static const int kStringValueFieldNumber = 11;
  const ::std::string& string_value() const;
  void set_string_value(const ::std::string& value);
  #if LANG_CXX11
  void set_string_value(::std::string&& value);
  #endif
  void set_string_value(const char* value);
  void set_string_value(const char* value, size_t size);
  ::std::string* mutable_string_value();
  ::std::string* release_string_value();
  void set_allocated_string_value(::std::string* string_value);

  // string wstring_value = 12;
  void clear_wstring_value();
  static const int kWstringValueFieldNumber = 12;
  const ::std::string& wstring_value() const;
  void set_wstring_value(const ::std::string& value);
  #if LANG_CXX11
  void set_wstring_value(::std::string&& value);
  #endif
  void set_wstring_value(const char* value);
  void set_wstring_value(const char* value, size_t size);
  ::std::string* mutable_wstring_value();
  ::std::string* release_wstring_value();
  void set_allocated_wstring_value(::std::string* wstring_value);

  // .codegen_test.StructType struct_value = 13;
  bool has_struct_value() const;
  void clear_struct_value();
  static const int kStructValueFieldNumber = 13;
  const ::codegen_test::StructType& struct_value() const;
  ::codegen_test::StructType* mutable_struct_value();
  ::codegen_test::StructType* release_struct_value();
  void set_allocated_struct_value(::codegen_test::StructType* struct_value);

  // bool bool_value = 1;
  void clear_bool_value();
  static const int kBoolValueFieldNumber = 1;
  bool bool_value() const;
  void set_bool_value(bool value);

  // int32 int32_value = 2;
  void clear_int32_value();
  static const int kInt32ValueFieldNumber = 2;
  ::google::protobuf::int32 int32_value() const;
  void set_int32_value(::google::protobuf::int32 value);

  // int64 int64_value = 4;
  void clear_int64_value();
  static const int kInt64ValueFieldNumber = 4;
  ::google::protobuf::int64 int64_value() const;
  void set_int64_value(::google::protobuf::int64 value);

  // uint32 uint32_value = 3;
  void clear_uint32_value();
  static const int kUint32ValueFieldNumber = 3;
  ::google::protobuf::uint32 uint32_value() const;
  void set_uint32_value(::google::protobuf::uint32 value);

  // sint32 sint32_value = 6;
  void clear_sint32_value();
  static const int kSint32ValueFieldNumber = 6;
  ::google::protobuf::int32 sint32_value() const;
  void set_sint32_value(::google::protobuf::int32 value);

  // uint64 uint64_value = 5;
  void clear_uint64_value();
  static const int kUint64ValueFieldNumber = 5;
  ::google::protobuf::uint64 uint64_value() const;
  void set_uint64_value(::google::protobuf::uint64 value);

  // sint64 sint64_value = 7;
  void clear_sint64_value();
  static const int kSint64ValueFieldNumber = 7;
  ::google::protobuf::int64 sint64_value() const;
  void set_sint64_value(::google::protobuf::int64 value);

  // double double_value = 9;
  void clear_double_value();
  static const int kDoubleValueFieldNumber = 9;
  double double_value() const;
  void set_double_value(double value);

  // float float_value = 8;
  void clear_float_value();
  static const int kFloatValueFieldNumber = 8;
  float float_value() const;
  void set_float_value(float value);

  // .codegen_test.EnumType enum_value = 10;
  void clear_enum_value();
  static const int kEnumValueFieldNumber = 10;
  ::codegen_test::EnumType enum_value() const;
  void set_enum_value(::codegen_test::EnumType value);

  // @@protoc_insertion_point(class_scope:codegen_test.Method_V_biuIUsSfdEAWM_args__)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr string_value_;
  ::google::protobuf::internal::ArenaStringPtr wstring_value_;
  ::codegen_test::StructType* struct_value_;
  bool bool_value_;
  ::google::protobuf::int32 int32_value_;
  ::google::protobuf::int64 int64_value_;
  ::google::protobuf::uint32 uint32_value_;
  ::google::protobuf::int32 sint32_value_;
  ::google::protobuf::uint64 uint64_value_;
  ::google::protobuf::int64 sint64_value_;
  double double_value_;
  float float_value_;
  int enum_value_;
  mutable int _cached_size_;
  friend struct  protobuf_codegen_5ftest_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// StructType

// bool bool_value = 1;
inline void StructType::clear_bool_value() {
  bool_value_ = false;
}
inline bool StructType::bool_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.StructType.bool_value)
  return bool_value_;
}
inline void StructType::set_bool_value(bool value) {
  
  bool_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.StructType.bool_value)
}

// int32 int32_value = 2;
inline void StructType::clear_int32_value() {
  int32_value_ = 0;
}
inline ::google::protobuf::int32 StructType::int32_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.StructType.int32_value)
  return int32_value_;
}
inline void StructType::set_int32_value(::google::protobuf::int32 value) {
  
  int32_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.StructType.int32_value)
}

// uint32 uint32_value = 3;
inline void StructType::clear_uint32_value() {
  uint32_value_ = 0u;
}
inline ::google::protobuf::uint32 StructType::uint32_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.StructType.uint32_value)
  return uint32_value_;
}
inline void StructType::set_uint32_value(::google::protobuf::uint32 value) {
  
  uint32_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.StructType.uint32_value)
}

// int64 int64_value = 4;
inline void StructType::clear_int64_value() {
  int64_value_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 StructType::int64_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.StructType.int64_value)
  return int64_value_;
}
inline void StructType::set_int64_value(::google::protobuf::int64 value) {
  
  int64_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.StructType.int64_value)
}

// uint64 uint64_value = 5;
inline void StructType::clear_uint64_value() {
  uint64_value_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 StructType::uint64_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.StructType.uint64_value)
  return uint64_value_;
}
inline void StructType::set_uint64_value(::google::protobuf::uint64 value) {
  
  uint64_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.StructType.uint64_value)
}

// sint32 sint32_value = 6;
inline void StructType::clear_sint32_value() {
  sint32_value_ = 0;
}
inline ::google::protobuf::int32 StructType::sint32_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.StructType.sint32_value)
  return sint32_value_;
}
inline void StructType::set_sint32_value(::google::protobuf::int32 value) {
  
  sint32_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.StructType.sint32_value)
}

// sint64 sint64_value = 7;
inline void StructType::clear_sint64_value() {
  sint64_value_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 StructType::sint64_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.StructType.sint64_value)
  return sint64_value_;
}
inline void StructType::set_sint64_value(::google::protobuf::int64 value) {
  
  sint64_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.StructType.sint64_value)
}

// float float_value = 8;
inline void StructType::clear_float_value() {
  float_value_ = 0;
}
inline float StructType::float_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.StructType.float_value)
  return float_value_;
}
inline void StructType::set_float_value(float value) {
  
  float_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.StructType.float_value)
}

// double double_value = 9;
inline void StructType::clear_double_value() {
  double_value_ = 0;
}
inline double StructType::double_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.StructType.double_value)
  return double_value_;
}
inline void StructType::set_double_value(double value) {
  
  double_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.StructType.double_value)
}

// .codegen_test.EnumType enum_value = 10;
inline void StructType::clear_enum_value() {
  enum_value_ = 0;
}
inline ::codegen_test::EnumType StructType::enum_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.StructType.enum_value)
  return static_cast< ::codegen_test::EnumType >(enum_value_);
}
inline void StructType::set_enum_value(::codegen_test::EnumType value) {
  
  enum_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.StructType.enum_value)
}

// string string_value = 11;
inline void StructType::clear_string_value() {
  string_value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StructType::string_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.StructType.string_value)
  return string_value_.GetNoArena();
}
inline void StructType::set_string_value(const ::std::string& value) {
  
  string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:codegen_test.StructType.string_value)
}
#if LANG_CXX11
inline void StructType::set_string_value(::std::string&& value) {
  
  string_value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:codegen_test.StructType.string_value)
}
#endif
inline void StructType::set_string_value(const char* value) {
  
  string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:codegen_test.StructType.string_value)
}
inline void StructType::set_string_value(const char* value, size_t size) {
  
  string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:codegen_test.StructType.string_value)
}
inline ::std::string* StructType::mutable_string_value() {
  
  // @@protoc_insertion_point(field_mutable:codegen_test.StructType.string_value)
  return string_value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StructType::release_string_value() {
  // @@protoc_insertion_point(field_release:codegen_test.StructType.string_value)
  
  return string_value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StructType::set_allocated_string_value(::std::string* string_value) {
  if (string_value != NULL) {
    
  } else {
    
  }
  string_value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), string_value);
  // @@protoc_insertion_point(field_set_allocated:codegen_test.StructType.string_value)
}

// string wstring_value = 12;
inline void StructType::clear_wstring_value() {
  wstring_value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StructType::wstring_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.StructType.wstring_value)
  return wstring_value_.GetNoArena();
}
inline void StructType::set_wstring_value(const ::std::string& value) {
  
  wstring_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:codegen_test.StructType.wstring_value)
}
#if LANG_CXX11
inline void StructType::set_wstring_value(::std::string&& value) {
  
  wstring_value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:codegen_test.StructType.wstring_value)
}
#endif
inline void StructType::set_wstring_value(const char* value) {
  
  wstring_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:codegen_test.StructType.wstring_value)
}
inline void StructType::set_wstring_value(const char* value, size_t size) {
  
  wstring_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:codegen_test.StructType.wstring_value)
}
inline ::std::string* StructType::mutable_wstring_value() {
  
  // @@protoc_insertion_point(field_mutable:codegen_test.StructType.wstring_value)
  return wstring_value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StructType::release_wstring_value() {
  // @@protoc_insertion_point(field_release:codegen_test.StructType.wstring_value)
  
  return wstring_value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StructType::set_allocated_wstring_value(::std::string* wstring_value) {
  if (wstring_value != NULL) {
    
  } else {
    
  }
  wstring_value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), wstring_value);
  // @@protoc_insertion_point(field_set_allocated:codegen_test.StructType.wstring_value)
}

// -------------------------------------------------------------------

// EnumType_wrapper__

// .codegen_test.EnumType value = 1;
inline void EnumType_wrapper__::clear_value() {
  value_ = 0;
}
inline ::codegen_test::EnumType EnumType_wrapper__::value() const {
  // @@protoc_insertion_point(field_get:codegen_test.EnumType_wrapper__.value)
  return static_cast< ::codegen_test::EnumType >(value_);
}
inline void EnumType_wrapper__::set_value(::codegen_test::EnumType value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.EnumType_wrapper__.value)
}

// -------------------------------------------------------------------

// Method_V_biuIUsSfdEAWM_args__

// bool bool_value = 1;
inline void Method_V_biuIUsSfdEAWM_args__::clear_bool_value() {
  bool_value_ = false;
}
inline bool Method_V_biuIUsSfdEAWM_args__::bool_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.Method_V_biuIUsSfdEAWM_args__.bool_value)
  return bool_value_;
}
inline void Method_V_biuIUsSfdEAWM_args__::set_bool_value(bool value) {
  
  bool_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.Method_V_biuIUsSfdEAWM_args__.bool_value)
}

// int32 int32_value = 2;
inline void Method_V_biuIUsSfdEAWM_args__::clear_int32_value() {
  int32_value_ = 0;
}
inline ::google::protobuf::int32 Method_V_biuIUsSfdEAWM_args__::int32_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.Method_V_biuIUsSfdEAWM_args__.int32_value)
  return int32_value_;
}
inline void Method_V_biuIUsSfdEAWM_args__::set_int32_value(::google::protobuf::int32 value) {
  
  int32_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.Method_V_biuIUsSfdEAWM_args__.int32_value)
}

// uint32 uint32_value = 3;
inline void Method_V_biuIUsSfdEAWM_args__::clear_uint32_value() {
  uint32_value_ = 0u;
}
inline ::google::protobuf::uint32 Method_V_biuIUsSfdEAWM_args__::uint32_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.Method_V_biuIUsSfdEAWM_args__.uint32_value)
  return uint32_value_;
}
inline void Method_V_biuIUsSfdEAWM_args__::set_uint32_value(::google::protobuf::uint32 value) {
  
  uint32_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.Method_V_biuIUsSfdEAWM_args__.uint32_value)
}

// int64 int64_value = 4;
inline void Method_V_biuIUsSfdEAWM_args__::clear_int64_value() {
  int64_value_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Method_V_biuIUsSfdEAWM_args__::int64_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.Method_V_biuIUsSfdEAWM_args__.int64_value)
  return int64_value_;
}
inline void Method_V_biuIUsSfdEAWM_args__::set_int64_value(::google::protobuf::int64 value) {
  
  int64_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.Method_V_biuIUsSfdEAWM_args__.int64_value)
}

// uint64 uint64_value = 5;
inline void Method_V_biuIUsSfdEAWM_args__::clear_uint64_value() {
  uint64_value_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Method_V_biuIUsSfdEAWM_args__::uint64_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.Method_V_biuIUsSfdEAWM_args__.uint64_value)
  return uint64_value_;
}
inline void Method_V_biuIUsSfdEAWM_args__::set_uint64_value(::google::protobuf::uint64 value) {
  
  uint64_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.Method_V_biuIUsSfdEAWM_args__.uint64_value)
}

// sint32 sint32_value = 6;
inline void Method_V_biuIUsSfdEAWM_args__::clear_sint32_value() {
  sint32_value_ = 0;
}
inline ::google::protobuf::int32 Method_V_biuIUsSfdEAWM_args__::sint32_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.Method_V_biuIUsSfdEAWM_args__.sint32_value)
  return sint32_value_;
}
inline void Method_V_biuIUsSfdEAWM_args__::set_sint32_value(::google::protobuf::int32 value) {
  
  sint32_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.Method_V_biuIUsSfdEAWM_args__.sint32_value)
}

// sint64 sint64_value = 7;
inline void Method_V_biuIUsSfdEAWM_args__::clear_sint64_value() {
  sint64_value_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Method_V_biuIUsSfdEAWM_args__::sint64_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.Method_V_biuIUsSfdEAWM_args__.sint64_value)
  return sint64_value_;
}
inline void Method_V_biuIUsSfdEAWM_args__::set_sint64_value(::google::protobuf::int64 value) {
  
  sint64_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.Method_V_biuIUsSfdEAWM_args__.sint64_value)
}

// float float_value = 8;
inline void Method_V_biuIUsSfdEAWM_args__::clear_float_value() {
  float_value_ = 0;
}
inline float Method_V_biuIUsSfdEAWM_args__::float_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.Method_V_biuIUsSfdEAWM_args__.float_value)
  return float_value_;
}
inline void Method_V_biuIUsSfdEAWM_args__::set_float_value(float value) {
  
  float_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.Method_V_biuIUsSfdEAWM_args__.float_value)
}

// double double_value = 9;
inline void Method_V_biuIUsSfdEAWM_args__::clear_double_value() {
  double_value_ = 0;
}
inline double Method_V_biuIUsSfdEAWM_args__::double_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.Method_V_biuIUsSfdEAWM_args__.double_value)
  return double_value_;
}
inline void Method_V_biuIUsSfdEAWM_args__::set_double_value(double value) {
  
  double_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.Method_V_biuIUsSfdEAWM_args__.double_value)
}

// .codegen_test.EnumType enum_value = 10;
inline void Method_V_biuIUsSfdEAWM_args__::clear_enum_value() {
  enum_value_ = 0;
}
inline ::codegen_test::EnumType Method_V_biuIUsSfdEAWM_args__::enum_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.Method_V_biuIUsSfdEAWM_args__.enum_value)
  return static_cast< ::codegen_test::EnumType >(enum_value_);
}
inline void Method_V_biuIUsSfdEAWM_args__::set_enum_value(::codegen_test::EnumType value) {
  
  enum_value_ = value;
  // @@protoc_insertion_point(field_set:codegen_test.Method_V_biuIUsSfdEAWM_args__.enum_value)
}

// string string_value = 11;
inline void Method_V_biuIUsSfdEAWM_args__::clear_string_value() {
  string_value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Method_V_biuIUsSfdEAWM_args__::string_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.Method_V_biuIUsSfdEAWM_args__.string_value)
  return string_value_.GetNoArena();
}
inline void Method_V_biuIUsSfdEAWM_args__::set_string_value(const ::std::string& value) {
  
  string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:codegen_test.Method_V_biuIUsSfdEAWM_args__.string_value)
}
#if LANG_CXX11
inline void Method_V_biuIUsSfdEAWM_args__::set_string_value(::std::string&& value) {
  
  string_value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:codegen_test.Method_V_biuIUsSfdEAWM_args__.string_value)
}
#endif
inline void Method_V_biuIUsSfdEAWM_args__::set_string_value(const char* value) {
  
  string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:codegen_test.Method_V_biuIUsSfdEAWM_args__.string_value)
}
inline void Method_V_biuIUsSfdEAWM_args__::set_string_value(const char* value, size_t size) {
  
  string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:codegen_test.Method_V_biuIUsSfdEAWM_args__.string_value)
}
inline ::std::string* Method_V_biuIUsSfdEAWM_args__::mutable_string_value() {
  
  // @@protoc_insertion_point(field_mutable:codegen_test.Method_V_biuIUsSfdEAWM_args__.string_value)
  return string_value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Method_V_biuIUsSfdEAWM_args__::release_string_value() {
  // @@protoc_insertion_point(field_release:codegen_test.Method_V_biuIUsSfdEAWM_args__.string_value)
  
  return string_value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Method_V_biuIUsSfdEAWM_args__::set_allocated_string_value(::std::string* string_value) {
  if (string_value != NULL) {
    
  } else {
    
  }
  string_value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), string_value);
  // @@protoc_insertion_point(field_set_allocated:codegen_test.Method_V_biuIUsSfdEAWM_args__.string_value)
}

// string wstring_value = 12;
inline void Method_V_biuIUsSfdEAWM_args__::clear_wstring_value() {
  wstring_value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Method_V_biuIUsSfdEAWM_args__::wstring_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.Method_V_biuIUsSfdEAWM_args__.wstring_value)
  return wstring_value_.GetNoArena();
}
inline void Method_V_biuIUsSfdEAWM_args__::set_wstring_value(const ::std::string& value) {
  
  wstring_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:codegen_test.Method_V_biuIUsSfdEAWM_args__.wstring_value)
}
#if LANG_CXX11
inline void Method_V_biuIUsSfdEAWM_args__::set_wstring_value(::std::string&& value) {
  
  wstring_value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:codegen_test.Method_V_biuIUsSfdEAWM_args__.wstring_value)
}
#endif
inline void Method_V_biuIUsSfdEAWM_args__::set_wstring_value(const char* value) {
  
  wstring_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:codegen_test.Method_V_biuIUsSfdEAWM_args__.wstring_value)
}
inline void Method_V_biuIUsSfdEAWM_args__::set_wstring_value(const char* value, size_t size) {
  
  wstring_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:codegen_test.Method_V_biuIUsSfdEAWM_args__.wstring_value)
}
inline ::std::string* Method_V_biuIUsSfdEAWM_args__::mutable_wstring_value() {
  
  // @@protoc_insertion_point(field_mutable:codegen_test.Method_V_biuIUsSfdEAWM_args__.wstring_value)
  return wstring_value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Method_V_biuIUsSfdEAWM_args__::release_wstring_value() {
  // @@protoc_insertion_point(field_release:codegen_test.Method_V_biuIUsSfdEAWM_args__.wstring_value)
  
  return wstring_value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Method_V_biuIUsSfdEAWM_args__::set_allocated_wstring_value(::std::string* wstring_value) {
  if (wstring_value != NULL) {
    
  } else {
    
  }
  wstring_value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), wstring_value);
  // @@protoc_insertion_point(field_set_allocated:codegen_test.Method_V_biuIUsSfdEAWM_args__.wstring_value)
}

// .codegen_test.StructType struct_value = 13;
inline bool Method_V_biuIUsSfdEAWM_args__::has_struct_value() const {
  return this != internal_default_instance() && struct_value_ != NULL;
}
inline void Method_V_biuIUsSfdEAWM_args__::clear_struct_value() {
  if (GetArenaNoVirtual() == NULL && struct_value_ != NULL) delete struct_value_;
  struct_value_ = NULL;
}
inline const ::codegen_test::StructType& Method_V_biuIUsSfdEAWM_args__::struct_value() const {
  // @@protoc_insertion_point(field_get:codegen_test.Method_V_biuIUsSfdEAWM_args__.struct_value)
  return struct_value_ != NULL ? *struct_value_
                         : *::codegen_test::StructType::internal_default_instance();
}
inline ::codegen_test::StructType* Method_V_biuIUsSfdEAWM_args__::mutable_struct_value() {
  
  if (struct_value_ == NULL) {
    struct_value_ = new ::codegen_test::StructType;
  }
  // @@protoc_insertion_point(field_mutable:codegen_test.Method_V_biuIUsSfdEAWM_args__.struct_value)
  return struct_value_;
}
inline ::codegen_test::StructType* Method_V_biuIUsSfdEAWM_args__::release_struct_value() {
  // @@protoc_insertion_point(field_release:codegen_test.Method_V_biuIUsSfdEAWM_args__.struct_value)
  
  ::codegen_test::StructType* temp = struct_value_;
  struct_value_ = NULL;
  return temp;
}
inline void Method_V_biuIUsSfdEAWM_args__::set_allocated_struct_value(::codegen_test::StructType* struct_value) {
  delete struct_value_;
  struct_value_ = struct_value;
  if (struct_value) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:codegen_test.Method_V_biuIUsSfdEAWM_args__.struct_value)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace codegen_test

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::codegen_test::EnumType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::codegen_test::EnumType>() {
  return ::codegen_test::EnumType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_codegen_5ftest_2eproto__INCLUDED
