// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_test.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "app_test.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace app {

namespace {

const ::google::protobuf::Descriptor* AppStruct_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AppStruct_reflection_ = NULL;
const ::google::protobuf::Descriptor* AppEnumValue_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AppEnumValue_reflection_ = NULL;
const ::google::protobuf::Descriptor* MethodWithParameters_args_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MethodWithParameters_args_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* AppEnum_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_app_5ftest_2eproto() {
  protobuf_AddDesc_app_5ftest_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "app_test.proto");
  GOOGLE_CHECK(file != NULL);
  AppStruct_descriptor_ = file->message_type(0);
  static const int AppStruct_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AppStruct, bool_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AppStruct, int_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AppStruct, enum_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AppStruct, string_value_),
  };
  AppStruct_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      AppStruct_descriptor_,
      AppStruct::default_instance_,
      AppStruct_offsets_,
      -1,
      -1,
      -1,
      sizeof(AppStruct),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AppStruct, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AppStruct, _is_default_instance_));
  AppEnumValue_descriptor_ = file->message_type(1);
  static const int AppEnumValue_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AppEnumValue, value_),
  };
  AppEnumValue_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      AppEnumValue_descriptor_,
      AppEnumValue::default_instance_,
      AppEnumValue_offsets_,
      -1,
      -1,
      -1,
      sizeof(AppEnumValue),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AppEnumValue, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AppEnumValue, _is_default_instance_));
  MethodWithParameters_args_descriptor_ = file->message_type(2);
  static const int MethodWithParameters_args_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MethodWithParameters_args, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MethodWithParameters_args, index_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MethodWithParameters_args, complext_data_),
  };
  MethodWithParameters_args_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MethodWithParameters_args_descriptor_,
      MethodWithParameters_args::default_instance_,
      MethodWithParameters_args_offsets_,
      -1,
      -1,
      -1,
      sizeof(MethodWithParameters_args),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MethodWithParameters_args, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MethodWithParameters_args, _is_default_instance_));
  AppEnum_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_app_5ftest_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      AppStruct_descriptor_, &AppStruct::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      AppEnumValue_descriptor_, &AppEnumValue::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MethodWithParameters_args_descriptor_, &MethodWithParameters_args::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_app_5ftest_2eproto() {
  delete AppStruct::default_instance_;
  delete AppStruct_reflection_;
  delete AppEnumValue::default_instance_;
  delete AppEnumValue_reflection_;
  delete MethodWithParameters_args::default_instance_;
  delete MethodWithParameters_args_reflection_;
}

void protobuf_AddDesc_app_5ftest_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fwrappers_2eproto();
  ::nanorpc2::protobuf_AddDesc_rpc_5fproto_2frpc_5ftypes_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016app_test.proto\022\003app\032\036google/protobuf/w"
    "rappers.proto\032\031rpc_proto/rpc_types.proto"
    "\"j\n\tAppStruct\022\022\n\nbool_value\030\001 \001(\010\022\021\n\tint"
    "_value\030\002 \001(\005\022 \n\nenum_value\030\003 \001(\0162\014.app.A"
    "ppEnum\022\024\n\014string_value\030\004 \001(\t\"1\n\014AppEnumV"
    "alue\022\033\n\005value\030\001 \001(\0162\014.app.AppEnum:\004\220\371+\001\""
    "\240\001\n\031MethodWithParameters_args\022*\n\004name\030\001 "
    "\001(\0132\034.google.protobuf.StringValue\022*\n\005ind"
    "ex\030\002 \001(\0132\033.google.protobuf.Int32Value\022%\n"
    "\rcomplext_data\030\003 \001(\0132\016.app.AppStruct:\004\210\371"
    "+\001*Y\n\007AppEnum\022\016\n\nEnumValue0\020\000\022\016\n\nEnumVal"
    "ue1\020\001\022\016\n\nEnumValue2\020\002\022\016\n\nEnumValue3\020\003\022\016\n"
    "\nEnumValue4\020\0042\343\010\n\010ITestApp\022I\n\tBoolValue\022"
    "\032.google.protobuf.BoolValue\032\032.google.pro"
    "tobuf.BoolValue\"\004\210\222,\001\022J\n\010IntValue\022\033.goog"
    "le.protobuf.Int32Value\032\033.google.protobuf"
    ".Int32Value\"\004\210\222,\001\0227\n\tEnumValue\022\021.app.App"
    "EnumValue\032\021.app.AppEnumValue\"\004\210\222,\001\022O\n\013St"
    "ringValue\022\034.google.protobuf.StringValue\032"
    "\034.google.protobuf.StringValue\"\004\210\222,\001\0223\n\013S"
    "tructValue\022\016.app.AppStruct\032\016.app.AppStru"
    "ct\"\004\210\222,\001\0226\n\016SyncVoidMethod\022\021.nanorpc2.Rp"
    "cVoid\032\021.nanorpc2.RpcVoid\022=\n\017AsyncVoidMet"
    "hod\022\021.nanorpc2.RpcVoid\032\021.nanorpc2.RpcVoi"
    "d\"\004\220\222,\001\022G\n\030SetStructReturnIntMethod\022\016.ap"
    "p.AppStruct\032\033.google.protobuf.Int32Value"
    "\022>\n\017GetStructMethod\022\033.google.protobuf.In"
    "t32Value\032\016.app.AppStruct\022@\n\030MethodWithou"
    "tParameters0\022\021.nanorpc2.RpcVoid\032\021.nanorp"
    "c2.RpcVoid\022I\n\030MethodWithoutParameters1\022\021"
    ".nanorpc2.RpcVoid\032\032.google.protobuf.Bool"
    "Value\022K\n\030MethodWithoutParameters2\022\021.nano"
    "rpc2.RpcVoid\032\034.google.protobuf.StringVal"
    "ue\022=\n\030MethodWithoutParameters3\022\021.nanorpc"
    "2.RpcVoid\032\016.app.AppStruct\022J\n\025MethodWithP"
    "arameters0\022\036.app.MethodWithParameters_ar"
    "gs\032\021.nanorpc2.RpcVoid\022S\n\025MethodWithParam"
    "eters1\022\036.app.MethodWithParameters_args\032\032"
    ".google.protobuf.BoolValue\022G\n\025MethodWith"
    "Parameters2\022\036.app.MethodWithParameters_a"
    "rgs\032\016.app.AppStructb\006proto3", 1627);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "app_test.proto", &protobuf_RegisterTypes);
  AppStruct::default_instance_ = new AppStruct();
  AppEnumValue::default_instance_ = new AppEnumValue();
  MethodWithParameters_args::default_instance_ = new MethodWithParameters_args();
  AppStruct::default_instance_->InitAsDefaultInstance();
  AppEnumValue::default_instance_->InitAsDefaultInstance();
  MethodWithParameters_args::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_app_5ftest_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_app_5ftest_2eproto {
  StaticDescriptorInitializer_app_5ftest_2eproto() {
    protobuf_AddDesc_app_5ftest_2eproto();
  }
} static_descriptor_initializer_app_5ftest_2eproto_;
const ::google::protobuf::EnumDescriptor* AppEnum_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AppEnum_descriptor_;
}
bool AppEnum_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AppStruct::kBoolValueFieldNumber;
const int AppStruct::kIntValueFieldNumber;
const int AppStruct::kEnumValueFieldNumber;
const int AppStruct::kStringValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AppStruct::AppStruct()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:app.AppStruct)
}

void AppStruct::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

AppStruct::AppStruct(const AppStruct& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:app.AppStruct)
}

void AppStruct::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  bool_value_ = false;
  int_value_ = 0;
  enum_value_ = 0;
  string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

AppStruct::~AppStruct() {
  // @@protoc_insertion_point(destructor:app.AppStruct)
  SharedDtor();
}

void AppStruct::SharedDtor() {
  string_value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void AppStruct::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AppStruct::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AppStruct_descriptor_;
}

const AppStruct& AppStruct::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_app_5ftest_2eproto();
  return *default_instance_;
}

AppStruct* AppStruct::default_instance_ = NULL;

AppStruct* AppStruct::New(::google::protobuf::Arena* arena) const {
  AppStruct* n = new AppStruct;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AppStruct::Clear() {
// @@protoc_insertion_point(message_clear_start:app.AppStruct)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(AppStruct, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<AppStruct*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(bool_value_, int_value_);
  enum_value_ = 0;
  string_value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool AppStruct::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:app.AppStruct)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool bool_value = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &bool_value_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_int_value;
        break;
      }

      // optional int32 int_value = 2;
      case 2: {
        if (tag == 16) {
         parse_int_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &int_value_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_enum_value;
        break;
      }

      // optional .app.AppEnum enum_value = 3;
      case 3: {
        if (tag == 24) {
         parse_enum_value:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_enum_value(static_cast< ::app::AppEnum >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_string_value;
        break;
      }

      // optional string string_value = 4;
      case 4: {
        if (tag == 34) {
         parse_string_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_string_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->string_value().data(), this->string_value().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "app.AppStruct.string_value"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:app.AppStruct)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:app.AppStruct)
  return false;
#undef DO_
}

void AppStruct::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:app.AppStruct)
  // optional bool bool_value = 1;
  if (this->bool_value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->bool_value(), output);
  }

  // optional int32 int_value = 2;
  if (this->int_value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->int_value(), output);
  }

  // optional .app.AppEnum enum_value = 3;
  if (this->enum_value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->enum_value(), output);
  }

  // optional string string_value = 4;
  if (this->string_value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->string_value().data(), this->string_value().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "app.AppStruct.string_value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->string_value(), output);
  }

  // @@protoc_insertion_point(serialize_end:app.AppStruct)
}

::google::protobuf::uint8* AppStruct::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:app.AppStruct)
  // optional bool bool_value = 1;
  if (this->bool_value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->bool_value(), target);
  }

  // optional int32 int_value = 2;
  if (this->int_value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->int_value(), target);
  }

  // optional .app.AppEnum enum_value = 3;
  if (this->enum_value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->enum_value(), target);
  }

  // optional string string_value = 4;
  if (this->string_value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->string_value().data(), this->string_value().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "app.AppStruct.string_value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->string_value(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:app.AppStruct)
  return target;
}

int AppStruct::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:app.AppStruct)
  int total_size = 0;

  // optional bool bool_value = 1;
  if (this->bool_value() != 0) {
    total_size += 1 + 1;
  }

  // optional int32 int_value = 2;
  if (this->int_value() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->int_value());
  }

  // optional .app.AppEnum enum_value = 3;
  if (this->enum_value() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->enum_value());
  }

  // optional string string_value = 4;
  if (this->string_value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->string_value());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AppStruct::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:app.AppStruct)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const AppStruct* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const AppStruct>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:app.AppStruct)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:app.AppStruct)
    MergeFrom(*source);
  }
}

void AppStruct::MergeFrom(const AppStruct& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:app.AppStruct)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.bool_value() != 0) {
    set_bool_value(from.bool_value());
  }
  if (from.int_value() != 0) {
    set_int_value(from.int_value());
  }
  if (from.enum_value() != 0) {
    set_enum_value(from.enum_value());
  }
  if (from.string_value().size() > 0) {

    string_value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.string_value_);
  }
}

void AppStruct::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:app.AppStruct)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AppStruct::CopyFrom(const AppStruct& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:app.AppStruct)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AppStruct::IsInitialized() const {

  return true;
}

void AppStruct::Swap(AppStruct* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AppStruct::InternalSwap(AppStruct* other) {
  std::swap(bool_value_, other->bool_value_);
  std::swap(int_value_, other->int_value_);
  std::swap(enum_value_, other->enum_value_);
  string_value_.Swap(&other->string_value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata AppStruct::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AppStruct_descriptor_;
  metadata.reflection = AppStruct_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AppStruct

// optional bool bool_value = 1;
void AppStruct::clear_bool_value() {
  bool_value_ = false;
}
 bool AppStruct::bool_value() const {
  // @@protoc_insertion_point(field_get:app.AppStruct.bool_value)
  return bool_value_;
}
 void AppStruct::set_bool_value(bool value) {
  
  bool_value_ = value;
  // @@protoc_insertion_point(field_set:app.AppStruct.bool_value)
}

// optional int32 int_value = 2;
void AppStruct::clear_int_value() {
  int_value_ = 0;
}
 ::google::protobuf::int32 AppStruct::int_value() const {
  // @@protoc_insertion_point(field_get:app.AppStruct.int_value)
  return int_value_;
}
 void AppStruct::set_int_value(::google::protobuf::int32 value) {
  
  int_value_ = value;
  // @@protoc_insertion_point(field_set:app.AppStruct.int_value)
}

// optional .app.AppEnum enum_value = 3;
void AppStruct::clear_enum_value() {
  enum_value_ = 0;
}
 ::app::AppEnum AppStruct::enum_value() const {
  // @@protoc_insertion_point(field_get:app.AppStruct.enum_value)
  return static_cast< ::app::AppEnum >(enum_value_);
}
 void AppStruct::set_enum_value(::app::AppEnum value) {
  
  enum_value_ = value;
  // @@protoc_insertion_point(field_set:app.AppStruct.enum_value)
}

// optional string string_value = 4;
void AppStruct::clear_string_value() {
  string_value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& AppStruct::string_value() const {
  // @@protoc_insertion_point(field_get:app.AppStruct.string_value)
  return string_value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AppStruct::set_string_value(const ::std::string& value) {
  
  string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:app.AppStruct.string_value)
}
 void AppStruct::set_string_value(const char* value) {
  
  string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:app.AppStruct.string_value)
}
 void AppStruct::set_string_value(const char* value, size_t size) {
  
  string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:app.AppStruct.string_value)
}
 ::std::string* AppStruct::mutable_string_value() {
  
  // @@protoc_insertion_point(field_mutable:app.AppStruct.string_value)
  return string_value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* AppStruct::release_string_value() {
  // @@protoc_insertion_point(field_release:app.AppStruct.string_value)
  
  return string_value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AppStruct::set_allocated_string_value(::std::string* string_value) {
  if (string_value != NULL) {
    
  } else {
    
  }
  string_value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), string_value);
  // @@protoc_insertion_point(field_set_allocated:app.AppStruct.string_value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AppEnumValue::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AppEnumValue::AppEnumValue()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:app.AppEnumValue)
}

void AppEnumValue::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

AppEnumValue::AppEnumValue(const AppEnumValue& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:app.AppEnumValue)
}

void AppEnumValue::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  value_ = 0;
}

AppEnumValue::~AppEnumValue() {
  // @@protoc_insertion_point(destructor:app.AppEnumValue)
  SharedDtor();
}

void AppEnumValue::SharedDtor() {
  if (this != default_instance_) {
  }
}

void AppEnumValue::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AppEnumValue::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AppEnumValue_descriptor_;
}

const AppEnumValue& AppEnumValue::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_app_5ftest_2eproto();
  return *default_instance_;
}

AppEnumValue* AppEnumValue::default_instance_ = NULL;

AppEnumValue* AppEnumValue::New(::google::protobuf::Arena* arena) const {
  AppEnumValue* n = new AppEnumValue;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AppEnumValue::Clear() {
// @@protoc_insertion_point(message_clear_start:app.AppEnumValue)
  value_ = 0;
}

bool AppEnumValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:app.AppEnumValue)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .app.AppEnum value = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_value(static_cast< ::app::AppEnum >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:app.AppEnumValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:app.AppEnumValue)
  return false;
#undef DO_
}

void AppEnumValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:app.AppEnumValue)
  // optional .app.AppEnum value = 1;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->value(), output);
  }

  // @@protoc_insertion_point(serialize_end:app.AppEnumValue)
}

::google::protobuf::uint8* AppEnumValue::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:app.AppEnumValue)
  // optional .app.AppEnum value = 1;
  if (this->value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->value(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:app.AppEnumValue)
  return target;
}

int AppEnumValue::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:app.AppEnumValue)
  int total_size = 0;

  // optional .app.AppEnum value = 1;
  if (this->value() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->value());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AppEnumValue::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:app.AppEnumValue)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const AppEnumValue* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const AppEnumValue>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:app.AppEnumValue)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:app.AppEnumValue)
    MergeFrom(*source);
  }
}

void AppEnumValue::MergeFrom(const AppEnumValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:app.AppEnumValue)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.value() != 0) {
    set_value(from.value());
  }
}

void AppEnumValue::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:app.AppEnumValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AppEnumValue::CopyFrom(const AppEnumValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:app.AppEnumValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AppEnumValue::IsInitialized() const {

  return true;
}

void AppEnumValue::Swap(AppEnumValue* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AppEnumValue::InternalSwap(AppEnumValue* other) {
  std::swap(value_, other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata AppEnumValue::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AppEnumValue_descriptor_;
  metadata.reflection = AppEnumValue_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AppEnumValue

// optional .app.AppEnum value = 1;
void AppEnumValue::clear_value() {
  value_ = 0;
}
 ::app::AppEnum AppEnumValue::value() const {
  // @@protoc_insertion_point(field_get:app.AppEnumValue.value)
  return static_cast< ::app::AppEnum >(value_);
}
 void AppEnumValue::set_value(::app::AppEnum value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:app.AppEnumValue.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MethodWithParameters_args::kNameFieldNumber;
const int MethodWithParameters_args::kIndexFieldNumber;
const int MethodWithParameters_args::kComplextDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MethodWithParameters_args::MethodWithParameters_args()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:app.MethodWithParameters_args)
}

void MethodWithParameters_args::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  name_ = const_cast< ::google::protobuf::StringValue*>(&::google::protobuf::StringValue::default_instance());
  index_ = const_cast< ::google::protobuf::Int32Value*>(&::google::protobuf::Int32Value::default_instance());
  complext_data_ = const_cast< ::app::AppStruct*>(&::app::AppStruct::default_instance());
}

MethodWithParameters_args::MethodWithParameters_args(const MethodWithParameters_args& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:app.MethodWithParameters_args)
}

void MethodWithParameters_args::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  name_ = NULL;
  index_ = NULL;
  complext_data_ = NULL;
}

MethodWithParameters_args::~MethodWithParameters_args() {
  // @@protoc_insertion_point(destructor:app.MethodWithParameters_args)
  SharedDtor();
}

void MethodWithParameters_args::SharedDtor() {
  if (this != default_instance_) {
    delete name_;
    delete index_;
    delete complext_data_;
  }
}

void MethodWithParameters_args::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MethodWithParameters_args::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MethodWithParameters_args_descriptor_;
}

const MethodWithParameters_args& MethodWithParameters_args::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_app_5ftest_2eproto();
  return *default_instance_;
}

MethodWithParameters_args* MethodWithParameters_args::default_instance_ = NULL;

MethodWithParameters_args* MethodWithParameters_args::New(::google::protobuf::Arena* arena) const {
  MethodWithParameters_args* n = new MethodWithParameters_args;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MethodWithParameters_args::Clear() {
// @@protoc_insertion_point(message_clear_start:app.MethodWithParameters_args)
  if (GetArenaNoVirtual() == NULL && name_ != NULL) delete name_;
  name_ = NULL;
  if (GetArenaNoVirtual() == NULL && index_ != NULL) delete index_;
  index_ = NULL;
  if (GetArenaNoVirtual() == NULL && complext_data_ != NULL) delete complext_data_;
  complext_data_ = NULL;
}

bool MethodWithParameters_args::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:app.MethodWithParameters_args)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .google.protobuf.StringValue name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_name()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_index;
        break;
      }

      // optional .google.protobuf.Int32Value index = 2;
      case 2: {
        if (tag == 18) {
         parse_index:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_index()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_complext_data;
        break;
      }

      // optional .app.AppStruct complext_data = 3;
      case 3: {
        if (tag == 26) {
         parse_complext_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_complext_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:app.MethodWithParameters_args)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:app.MethodWithParameters_args)
  return false;
#undef DO_
}

void MethodWithParameters_args::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:app.MethodWithParameters_args)
  // optional .google.protobuf.StringValue name = 1;
  if (this->has_name()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->name_, output);
  }

  // optional .google.protobuf.Int32Value index = 2;
  if (this->has_index()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->index_, output);
  }

  // optional .app.AppStruct complext_data = 3;
  if (this->has_complext_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->complext_data_, output);
  }

  // @@protoc_insertion_point(serialize_end:app.MethodWithParameters_args)
}

::google::protobuf::uint8* MethodWithParameters_args::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:app.MethodWithParameters_args)
  // optional .google.protobuf.StringValue name = 1;
  if (this->has_name()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->name_, target);
  }

  // optional .google.protobuf.Int32Value index = 2;
  if (this->has_index()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *this->index_, target);
  }

  // optional .app.AppStruct complext_data = 3;
  if (this->has_complext_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, *this->complext_data_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:app.MethodWithParameters_args)
  return target;
}

int MethodWithParameters_args::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:app.MethodWithParameters_args)
  int total_size = 0;

  // optional .google.protobuf.StringValue name = 1;
  if (this->has_name()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->name_);
  }

  // optional .google.protobuf.Int32Value index = 2;
  if (this->has_index()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->index_);
  }

  // optional .app.AppStruct complext_data = 3;
  if (this->has_complext_data()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->complext_data_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MethodWithParameters_args::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:app.MethodWithParameters_args)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const MethodWithParameters_args* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MethodWithParameters_args>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:app.MethodWithParameters_args)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:app.MethodWithParameters_args)
    MergeFrom(*source);
  }
}

void MethodWithParameters_args::MergeFrom(const MethodWithParameters_args& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:app.MethodWithParameters_args)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.has_name()) {
    mutable_name()->::google::protobuf::StringValue::MergeFrom(from.name());
  }
  if (from.has_index()) {
    mutable_index()->::google::protobuf::Int32Value::MergeFrom(from.index());
  }
  if (from.has_complext_data()) {
    mutable_complext_data()->::app::AppStruct::MergeFrom(from.complext_data());
  }
}

void MethodWithParameters_args::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:app.MethodWithParameters_args)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MethodWithParameters_args::CopyFrom(const MethodWithParameters_args& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:app.MethodWithParameters_args)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MethodWithParameters_args::IsInitialized() const {

  return true;
}

void MethodWithParameters_args::Swap(MethodWithParameters_args* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MethodWithParameters_args::InternalSwap(MethodWithParameters_args* other) {
  std::swap(name_, other->name_);
  std::swap(index_, other->index_);
  std::swap(complext_data_, other->complext_data_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MethodWithParameters_args::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MethodWithParameters_args_descriptor_;
  metadata.reflection = MethodWithParameters_args_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MethodWithParameters_args

// optional .google.protobuf.StringValue name = 1;
bool MethodWithParameters_args::has_name() const {
  return !_is_default_instance_ && name_ != NULL;
}
void MethodWithParameters_args::clear_name() {
  if (GetArenaNoVirtual() == NULL && name_ != NULL) delete name_;
  name_ = NULL;
}
const ::google::protobuf::StringValue& MethodWithParameters_args::name() const {
  // @@protoc_insertion_point(field_get:app.MethodWithParameters_args.name)
  return name_ != NULL ? *name_ : *default_instance_->name_;
}
::google::protobuf::StringValue* MethodWithParameters_args::mutable_name() {
  
  if (name_ == NULL) {
    name_ = new ::google::protobuf::StringValue;
  }
  // @@protoc_insertion_point(field_mutable:app.MethodWithParameters_args.name)
  return name_;
}
::google::protobuf::StringValue* MethodWithParameters_args::release_name() {
  // @@protoc_insertion_point(field_release:app.MethodWithParameters_args.name)
  
  ::google::protobuf::StringValue* temp = name_;
  name_ = NULL;
  return temp;
}
void MethodWithParameters_args::set_allocated_name(::google::protobuf::StringValue* name) {
  delete name_;
  if (name != NULL && name->GetArena() != NULL) {
    ::google::protobuf::StringValue* new_name = new ::google::protobuf::StringValue;
    new_name->CopyFrom(*name);
    name = new_name;
  }
  name_ = name;
  if (name) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:app.MethodWithParameters_args.name)
}

// optional .google.protobuf.Int32Value index = 2;
bool MethodWithParameters_args::has_index() const {
  return !_is_default_instance_ && index_ != NULL;
}
void MethodWithParameters_args::clear_index() {
  if (GetArenaNoVirtual() == NULL && index_ != NULL) delete index_;
  index_ = NULL;
}
const ::google::protobuf::Int32Value& MethodWithParameters_args::index() const {
  // @@protoc_insertion_point(field_get:app.MethodWithParameters_args.index)
  return index_ != NULL ? *index_ : *default_instance_->index_;
}
::google::protobuf::Int32Value* MethodWithParameters_args::mutable_index() {
  
  if (index_ == NULL) {
    index_ = new ::google::protobuf::Int32Value;
  }
  // @@protoc_insertion_point(field_mutable:app.MethodWithParameters_args.index)
  return index_;
}
::google::protobuf::Int32Value* MethodWithParameters_args::release_index() {
  // @@protoc_insertion_point(field_release:app.MethodWithParameters_args.index)
  
  ::google::protobuf::Int32Value* temp = index_;
  index_ = NULL;
  return temp;
}
void MethodWithParameters_args::set_allocated_index(::google::protobuf::Int32Value* index) {
  delete index_;
  if (index != NULL && index->GetArena() != NULL) {
    ::google::protobuf::Int32Value* new_index = new ::google::protobuf::Int32Value;
    new_index->CopyFrom(*index);
    index = new_index;
  }
  index_ = index;
  if (index) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:app.MethodWithParameters_args.index)
}

// optional .app.AppStruct complext_data = 3;
bool MethodWithParameters_args::has_complext_data() const {
  return !_is_default_instance_ && complext_data_ != NULL;
}
void MethodWithParameters_args::clear_complext_data() {
  if (GetArenaNoVirtual() == NULL && complext_data_ != NULL) delete complext_data_;
  complext_data_ = NULL;
}
const ::app::AppStruct& MethodWithParameters_args::complext_data() const {
  // @@protoc_insertion_point(field_get:app.MethodWithParameters_args.complext_data)
  return complext_data_ != NULL ? *complext_data_ : *default_instance_->complext_data_;
}
::app::AppStruct* MethodWithParameters_args::mutable_complext_data() {
  
  if (complext_data_ == NULL) {
    complext_data_ = new ::app::AppStruct;
  }
  // @@protoc_insertion_point(field_mutable:app.MethodWithParameters_args.complext_data)
  return complext_data_;
}
::app::AppStruct* MethodWithParameters_args::release_complext_data() {
  // @@protoc_insertion_point(field_release:app.MethodWithParameters_args.complext_data)
  
  ::app::AppStruct* temp = complext_data_;
  complext_data_ = NULL;
  return temp;
}
void MethodWithParameters_args::set_allocated_complext_data(::app::AppStruct* complext_data) {
  delete complext_data_;
  complext_data_ = complext_data;
  if (complext_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:app.MethodWithParameters_args.complext_data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace app

// @@protoc_insertion_point(global_scope)
