mkdir  "include\nano_rpc"

copy "src\basictypes.hpp" "include\nano_rpc"
copy "src\buffer_pool.hpp" "include\nano_rpc"
copy "src\callback.hpp" "include\nano_rpc"
copy "src\named_pipe_connector.hpp" "include\nano_rpc"
copy "src\named_pipe_rpc_channel.hpp" "include\nano_rpc"
copy "src\nano_rpc.hpp" "include\nano_rpc"
copy "src\object_pool.hpp" "include\nano_rpc"
copy "src\rpc_channel.hpp" "include\nano_rpc"
copy "src\rpc_client.hpp" "include\nano_rpc"
copy "src\rpc_controller.hpp" "include\nano_rpc"
copy "src\rpc_event_service.hpp" "include\nano_rpc"
copy "src\rpc_message_sender.hpp" "include\nano_rpc"
copy "src\rpc_object_manager.hpp" "include\nano_rpc"
copy "src\rpc_server.hpp" "include\nano_rpc"
copy "src\rpc_service.hpp" "include\nano_rpc"
copy "src\rpc_stub.hpp" "include\nano_rpc"
copy "src\RpcMessageTypes.pb.h" "include\nano_rpc"
copy "src\string_conversion.cpp" "include\nano_rpc"
copy "src\string_conversion.hpp" "include\nano_rpc"
copy "src\synchronization_primitives.hpp" "include\nano_rpc"


